// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (created_at) VALUES ($1) RETURNING id, created_at
`

func (q *Queries) CreateChat(ctx context.Context, createdAt pgtype.Timestamptz) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, createdAt)
	var i Chat
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats WHERE id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteChat, id)
	return err
}

const getChat = `-- name: GetChat :one
SELECT id, created_at FROM chats WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id int32) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getChatByTwoUsers = `-- name: GetChatByTwoUsers :one
SELECT c.id, c.created_at FROM chats c
JOIN chat_participants cp1 ON cp1.chat_id = c.id AND cp1.user_id = $1
JOIN chat_participants cp2 ON cp2.chat_id = c.id AND cp2.user_id = $2
`

type GetChatByTwoUsersParams struct {
	UserID   int32 `json:"user_id"`
	UserID_2 int32 `json:"user_id_2"`
}

func (q *Queries) GetChatByTwoUsers(ctx context.Context, arg GetChatByTwoUsersParams) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByTwoUsers, arg.UserID, arg.UserID_2)
	var i Chat
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listChatsByUserID = `-- name: ListChatsByUserID :many
SELECT c.id, c.created_at FROM chats c
JOIN chat_participants cp ON cp.chat_id = c.id
WHERE cp.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListChatsByUserID(ctx context.Context, userID int32) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listChatsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
