// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats_participants.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatParticipant = `-- name: CreateChatParticipant :exec
INSERT INTO chat_participants (chat_id, user_id, joined_at) VALUES ($1, $2, $3)
`

type CreateChatParticipantParams struct {
	ChatID   int32              `json:"chat_id"`
	UserID   int32              `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) CreateChatParticipant(ctx context.Context, arg CreateChatParticipantParams) error {
	_, err := q.db.Exec(ctx, createChatParticipant, arg.ChatID, arg.UserID, arg.JoinedAt)
	return err
}

const deleteChatParticipant = `-- name: DeleteChatParticipant :exec
DELETE FROM chat_participants WHERE chat_id = $1 AND user_id = $2
`

type DeleteChatParticipantParams struct {
	ChatID int32 `json:"chat_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteChatParticipant(ctx context.Context, arg DeleteChatParticipantParams) error {
	_, err := q.db.Exec(ctx, deleteChatParticipant, arg.ChatID, arg.UserID)
	return err
}

const getChatParticipantByChatIDAndUserID = `-- name: GetChatParticipantByChatIDAndUserID :one
SELECT chat_id, user_id, joined_at FROM chat_participants WHERE chat_id = $1 AND user_id = $2
`

type GetChatParticipantByChatIDAndUserIDParams struct {
	ChatID int32 `json:"chat_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetChatParticipantByChatIDAndUserID(ctx context.Context, arg GetChatParticipantByChatIDAndUserIDParams) (ChatParticipant, error) {
	row := q.db.QueryRow(ctx, getChatParticipantByChatIDAndUserID, arg.ChatID, arg.UserID)
	var i ChatParticipant
	err := row.Scan(&i.ChatID, &i.UserID, &i.JoinedAt)
	return i, err
}

const listChatParticipantsByChatID = `-- name: ListChatParticipantsByChatID :many
SELECT chat_id, user_id, joined_at FROM chat_participants WHERE chat_id = $1 ORDER BY joined_at
`

func (q *Queries) ListChatParticipantsByChatID(ctx context.Context, chatID int32) ([]ChatParticipant, error) {
	rows, err := q.db.Query(ctx, listChatParticipantsByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatParticipant
	for rows.Next() {
		var i ChatParticipant
		if err := rows.Scan(&i.ChatID, &i.UserID, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
