// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFeed = `-- name: GetFeed :many
SELECT
    p.id, p.user_id, p.title, p.content, p.created_at, p.updated_at,
    COALESCE(l.likes_count, 0)::bigint AS likes_count,
    COALESCE(c.comments_count, 0)::bigint AS comments_count,
    (COALESCE(l.likes_count, 0) * 0.5
     + COALESCE(c.comments_count, 0) * 2
     - EXTRACT(EPOCH FROM (NOW() - p.created_at)) / 3600
    )::float8 AS score
FROM posts p
JOIN follows f ON p.user_id = f.following_id AND f.follower_id = $1
LEFT JOIN (SELECT post_id, COUNT(*) AS likes_count FROM likes GROUP BY post_id) l ON l.post_id = p.id
LEFT JOIN (SELECT post_id, COUNT(*) AS comments_count FROM comments GROUP BY post_id) c ON c.post_id = p.id
ORDER BY score DESC
LIMIT $2 OFFSET $3
`

type GetFeedParams struct {
	FollowerID int32 `json:"follower_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type GetFeedRow struct {
	ID            int32              `json:"id"`
	UserID        int32              `json:"user_id"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LikesCount    int64              `json:"likes_count"`
	CommentsCount int64              `json:"comments_count"`
	Score         float64            `json:"score"`
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) ([]GetFeedRow, error) {
	rows, err := q.db.Query(ctx, getFeed, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedRow
	for rows.Next() {
		var i GetFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LikesCount,
			&i.CommentsCount,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
