// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package repo

import (
	"context"
)

const likePost = `-- name: LikePost :one
INSERT INTO likes (user_id, post_id) VALUES ($1, $2) RETURNING id, user_id, post_id, created_at
`

type LikePostParams struct {
	UserID int32 `json:"user_id"`
	PostID int32 `json:"post_id"`
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) (Like, error) {
	row := q.db.QueryRow(ctx, likePost, arg.UserID, arg.PostID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.CreatedAt,
	)
	return i, err
}

const listLikesByPostID = `-- name: ListLikesByPostID :many
SELECT id, user_id, post_id, created_at FROM likes WHERE post_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListLikesByPostID(ctx context.Context, postID int32) ([]Like, error) {
	rows, err := q.db.Query(ctx, listLikesByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Like
	for rows.Next() {
		var i Like
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PostID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlikePost = `-- name: UnlikePost :exec
DELETE FROM likes WHERE user_id = $1 AND post_id = $2
`

type UnlikePostParams struct {
	UserID int32 `json:"user_id"`
	PostID int32 `json:"post_id"`
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) error {
	_, err := q.db.Exec(ctx, unlikePost, arg.UserID, arg.PostID)
	return err
}
