// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, sender_id, content, created_at, is_read)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, chat_id, sender_id, content, created_at, is_read
`

type CreateMessageParams struct {
	ChatID    int32              `json:"chat_id"`
	SenderID  int32              `json:"sender_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IsRead    bool               `json:"is_read"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChatID,
		arg.SenderID,
		arg.Content,
		arg.CreatedAt,
		arg.IsRead,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.IsRead,
	)
	return i, err
}

const listMessagesByChatID = `-- name: ListMessagesByChatID :many
SELECT id, chat_id, sender_id, content, created_at, is_read
FROM messages
WHERE chat_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMessagesByChatIDParams struct {
	ChatID int32 `json:"chat_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMessagesByChatID(ctx context.Context, arg ListMessagesByChatIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByChatID, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
