// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCommentsByPostID(ctx context.Context, postID int32) (int64, error)
	CountFollowers(ctx context.Context, followingID int32) (int64, error)
	CountFollowing(ctx context.Context, followerID int32) (int64, error)
	CountLikesByPostID(ctx context.Context, postID int32) (int64, error)
	CountPostsByUserID(ctx context.Context, userID int32) (int64, error)
	CreateChat(ctx context.Context, createdAt pgtype.Timestamptz) (Chat, error)
	CreateChatParticipant(ctx context.Context, arg CreateChatParticipantParams) error
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteChat(ctx context.Context, id int32) error
	DeleteChatParticipant(ctx context.Context, arg DeleteChatParticipantParams) error
	DeleteComment(ctx context.Context, id int32) error
	DeletePost(ctx context.Context, id int32) error
	FindCommentByID(ctx context.Context, id int32) (Comment, error)
	FindPostByID(ctx context.Context, id int32) (Post, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id int32) (User, error)
	FollowUser(ctx context.Context, arg FollowUserParams) (Follow, error)
	GetChat(ctx context.Context, id int32) (Chat, error)
	GetChatByTwoUsers(ctx context.Context, arg GetChatByTwoUsersParams) (Chat, error)
	GetChatParticipantByChatIDAndUserID(ctx context.Context, arg GetChatParticipantByChatIDAndUserIDParams) (ChatParticipant, error)
	LikePost(ctx context.Context, arg LikePostParams) (Like, error)
	ListChatParticipantsByChatID(ctx context.Context, arg ListChatParticipantsByChatIDParams) ([]ChatParticipant, error)
	ListChatsByUserID(ctx context.Context, arg ListChatsByUserIDParams) ([]Chat, error)
	ListCommentsByPostID(ctx context.Context, arg ListCommentsByPostIDParams) ([]Comment, error)
	ListFollowers(ctx context.Context, arg ListFollowersParams) ([]Follow, error)
	ListFollowing(ctx context.Context, arg ListFollowingParams) ([]Follow, error)
	ListLikesByPostID(ctx context.Context, arg ListLikesByPostIDParams) ([]Like, error)
	ListPostsByUserID(ctx context.Context, arg ListPostsByUserIDParams) ([]Post, error)
	ListUsers(ctx context.Context) ([]User, error)
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) error
	UnlikePost(ctx context.Context, arg UnlikePostParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
